name: Webpage Information Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟自动运行一次
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      run_now:
        description: '是否立即运行'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4  # 安装 beautifulsoup4

    - name: Get Information & Update File
      run: |
        python script.py
        cat data.txt
        cat latest.txt

    - name: Check File Update
      id: file_check
      run: |
        echo "modified=$(git diff --name-only)" >> $GITHUB_ENV

    - name: If File Updated, Push to GitHub
      if: contains(env.modified, 'data.txt') || contains(env.modified, 'latest.txt')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add data.txt latest.txt
        git commit -m "Update information and latest time"
        git push
