name: Webpage Information Checker
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
      
    - name: Get Information & Update File
      run: |
        python script.py

    - name: Check File Update
      id: file_check
      run: |
        echo "::set-output name=modified::$(git diff --name-only)"
      
    - name: If File Updated, Push to GitHub
      if: contains(steps.file_check.outputs.modified, 'data.txt') || contains(steps.file_check.outputs.modified, 'latest.txt')
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.txt latest.txt
        git commit -m "Update information and latest time"
        git push
