name: Webpage Information Checker

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟自动运行一次
  workflow_dispatch:  # 允许手动触发工作流
    inputs:
      run_now:
        description: '是否立即运行'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 更新为 v3

    - name: Set up Python
      uses: actions/setup-python@v3  # 更新为 v3
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4  # 安装 beautifulsoup4

    - name: Get Information & Update File
      run: |
        python script.py
        cat data.txt
        cat latest.txt

    - name: Check File Update
      id: file_check
      run: |
        # 获取当前工作区的变更文件
        git diff --name-only > modified_files.txt
        # 检查文件是否有变动
        if grep -q "data.txt" modified_files.txt || grep -q "latest.txt" modified_files.txt; then
          echo "MODIFIED=true" >> $GITHUB_ENV
        else
          echo "MODIFIED=false" >> $GITHUB_ENV
        fi

    - name: If File Updated, Push to GitHub
      if: env.MODIFIED == 'true'
      run: |
        # 配置 Git 用户信息
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 确保文件添加并提交
        git status
        git add data.txt latest.txt
        git commit -m "Update information and latest time"
        git push
